version: '3.8'

services:
  health-diary:
    build:
      context: ./health-diary-ui
      dockerfile: Dockerfile
    image: ghcr.io/mornemaritz/health-diary/health-diary-ui:v0.19.1
    container_name: health-diary-ui
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - webproxy

  nginx:
    image: nginx:1.25-alpine
    container_name: hd-nginx
    restart: unless-stopped
    ports:
      - "8880:80"
      - "8443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/nginx/certs:ro
    depends_on:
      - health-diary
    networks:
      - webproxy

networks:
  webproxy:
    driver: bridge
