name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  actions: read
  contents: write
  packages: write

jobs:
  build-test-tag:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semver.outputs.next }}
      old-version: ${{ steps.semver.outputs.current }}
    
    steps:
    - uses: actions/checkout@v5

    - name: Set up Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '22'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Install Dependencies
      working-directory: ./health-diary-ui
      run: npm ci

    # TODO: Enable tests once they are implemented
    # - name: Run Tests
    #   working-directory: ./health-diary-ui
    #   run: npm test

    - name: Build React App
      working-directory: ./health-diary-ui
      run: npm run build

    - name: setup git config for pushing version tag
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "noreply.githubactionsbot@no-mail.com"

    - name: Bump Version and Create Tag
      id: semver
      uses: ietf-tools/semver-action@v1
      with:
        token: ${{ github.token }}
        branch: main
        noVersionBumpBehavior: warn

    - name: write version to package.json and k8s manifest
      if: ${{ steps.semver.outputs.next != steps.semver.outputs.current }}
      run: |
        cd ./health-diary-ui
        npm version ${{ steps.semver.outputs.next }} --no-git-tag-version
        cat package.json
        sed -i "s|health-diary-ui:.*|health-diary-ui:${{ steps.semver.outputs.next }}|g" ../.k8s/health-diary.yaml
        cat ../.k8s/health-diary.yaml
        git add ../.k8s/health-diary.yaml
        git add .
        git commit -m"chore(release) ${{ steps.semver.outputs.next }}"
        git tag ${{ steps.semver.outputs.next }}

    - name: Push Changes and Tags
      if: ${{ steps.semver.outputs.next != steps.semver.outputs.current }}
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        tags: true

    - name: Update CHANGELOG
      id: changelog
      uses: requarks/changelog-action@v1
      with:
        token: ${{ github.token }}
        tag: ${{ steps.semver.outputs.next }}
        changelogFilePath: ./health-diary-ui/CHANGELOG.md
        excludeTypes: chore,docs,doc,perf

    - name: Create Release
      if: steps.semver.outputs.next != steps.semver.outputs.current
      uses: ncipollo/release-action@v1.12.0
      with:
        allowUpdates: true
        draft: false
        makeLatest: true
        tag: ${{ steps.semver.outputs.next }}
        name: Release ${{ steps.semver.outputs.next }}
        body: ${{ steps.changelog.outputs.changes }}
        token: ${{ github.token }}

    - name: Commit CHANGELOG.md
      if: ${{ steps.semver.outputs.next != steps.semver.outputs.current }}
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: main
        commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
        file_pattern: ./health-diary-ui/CHANGELOG.md

  docker:
    needs: build-test-tag
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && needs.build-test-tag.outputs.version != needs.build-test-tag.outputs.old-version

    steps:
    - uses: actions/checkout@v5
      with:
        ref: ${{ github.ref }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./health-diary-ui
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/health-diary-ui:latest
          ghcr.io/${{ github.repository }}/health-diary-ui:${{ needs.build-test-tag.outputs.version }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    needs: [docker, build-test-tag]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && needs.build-test-tag.outputs.version != needs.build-test-tag.outputs.old-version

    steps:
    - name: Checkout rendered gitops repository
      uses: actions/checkout@v4
      with:
        repository: mornemaritz/gitops-helm-application-repo
        ref: 'main'
        token:  ${{ secrets.ACTIONS_GITHUB_REPOSITORY_TOKEN }}
    - name: setup git config for gitops repo
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "noreply.githubactionsbot@no-mail.com"
    - name: Update Helm values with new image tag
      run: |
        sed -i "s|tag: .*|tag: \"${{ needs.build-test-tag.outputs.version }}\"|g" ./configurations/local-microk8s/health-diary/values.yaml
        cat ./configurations/local-microk8s/health-diary/values.yaml
    - name: Commit and Push changes to GitOps repo
      run: |
        git add .
        git commit -m"Bake manifest ${{ needs.build-test-tag.outputs.version }}"
        git push origin main
        git tag ${{ needs.build-test-tag.outputs.version }}
        git push --tags origin main
